apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-tracer
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: http-tracer
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: http-tracer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: http-tracer
subjects:
- kind: ServiceAccount
  name: http-tracer
  namespace: kube-system
